### ISSUE TITLE
Error on dependencies

### ISSUE THREAD

**Issue by trustn0one** [mpromonet/libv4l2cpp#1]
I got this error after typing make command

Submodule 'v4l2wrapper' (https://github.com/mpromonet/v4l2wrapper) registered for path 'v4l2wrapper'
Cloning into 'v4l2wrapper'...
error: The requested URL returned error: 403 while accessing https://github.com/mpromonet/v4l2wrapper/info/refs
fatal: HTTP request failed
Clone of 'https://github.com/mpromonet/v4l2wrapper' into submodule path 'v4l2wrapper' failed
CMakeFiles/git_update.dir/build.make:49: recipe for target 'CMakeFiles/git_update' failed
make[2]: **\* [CMakeFiles/git_update] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/git_update.dir/all' failed
make[1]: **\* [CMakeFiles/git_update.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by trustn0one** [comment]
i solved doing this:

```
  rm -rf v4l2wrapper
  git submodule update
```

**Comment by mpromonet** [comment]
I guess you speak about an other project (probably h264_v4l2_rtspserver) that use v4l2wrapper as a submodule, isn 't it ?
