### ISSUE TITLE
Add `-fPIC` option in Makefile

### ISSUE THREAD

**Issue by mattdibi** [mpromonet/libv4l2cpp#20]
Hi,

first and foremost thank you for publishing this library, it's been a godsend for me.
I have a minor issue in building it though. When I added you library as a dependency for my project the following showed up:

```
/usr/bin/ld: ../../../third_party/libv4l2cpp/libv4l2wrapper.a(V4l2Capture.o): relocation R_X86_64_PC32 against symbol `_ZTV11V4l2Capture' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

By adding the following to your Makefile:
```diff
diff --git a/Makefile b/Makefile
index d012f22..de84da7 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 CXXFLAGS = -W -pthread -g -pipe $(EXTRA_CXXFLAGS)
-CXXFLAGS += -I inc
+CXXFLAGS += -I inc -fPIC
 RM = rm -rf
 CXX ?= $(CROSS)g++
 AR ?= $(CROSS)ar
```

and recompiling your library, I was able to successfully compile my project.

Given that the `-fPIC` is used to generate position-independent code (PIC) and thus making your project suitable for inclusion in a library (which is my case), could it have sense to include this fix in your Makefile?

If you think this make sense I'll open a PR with the addition here.

**Comment by mpromonet** [comment]
Hi,

Nice you find this helpful, I did that to share the code between several projects.
I guess you are building a shared library linking to the static library.   
A way to do this could be to run make with `-DEXTRA_CXXFLAGS=fPIC`.

Best Regards,
Michel.

**Comment by mattdibi** [comment]
Hi,

thank you for your suggestion. The actual syntax is:

```
make EXTRA_CXXFLAGS=-fPIC
```

and it works flawlessly. This is way better than the solution I proposed because it is more flexible. In my defense I searched for a way to pass the `-fPIC` option with the `make` command but, apparently, not deep enough :D

Anyway thank you very much for the help!
