### ISSUE TITLE
IOTYPE_MMAP

### ISSUE THREAD

**Issue by timurzdev** [mpromonet/libv4l2cpp#22]
V4L2DeviceParameters param("/dev/video0", V4L2_PIX_FMT_RGBA32, 400, 800, 60, IOTYPE_MMAP, 0);
    V4l2Capture* videoCapture = V4l2Capture::create(param);

while debugging i found that it is m_iotype=IOTYPE_READWRITE

**Comment by mpromonet** [comment]
Hi @moskalt 

This depends on your device, usually a device capture support mmap access, read interface is a fallback.

Best Regards,
Michel.

**Comment by timurzdev** [comment]
@mpromonet Hi,I've thought that was a reason of crashes(bad_alloc), tried prev version, still crashing, do u have any idea?
my repo: https://github.com/moskalt/LibtorchDetection/blob/main/src/detection.cpp

**Comment by timurzdev** [comment]
![image](https://user-images.githubusercontent.com/58132831/114544807-5674a300-9c85-11eb-9b54-f06d410360a1.png)
it crashes here, I have no idea why, I use droidcam(tried wireless and usb connection)

**Comment by mpromonet** [comment]
Hi,

Removing ```#include "torch/torch.h"``` in your code, build and run without problems. I did not try to install it.
Maybe some collision with pytorch ?

Best Regards,
Michel.

**Comment by timurzdev** [comment]
@mpromonet Thanks!

**Comment by mpromonet** [comment]
Hi @moskalt 

Finally I install torch with : 
```
cd thirdparty && wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip && unzip *.zip && cd -
```
and then run
```
cmake .
make
src/main
```
It simply run without any bad alloc or other problem, it just print "YES"... 

This seems expected behaviour of code
```
int main(){
    V4L2DeviceParameters param("/dev/video0", V4L2_PIX_FMT_RGB24, 400, 400, 10, IOTYPE_MMAP, 0);
    V4l2Capture* videoCapture = V4l2Capture::create(param);
    std::cout << "YES" << std::endl;
}
```

Best Regards,
Michel.

**Comment by timurzdev** [comment]
Hi @mpromonet 

I just linked torch to my **detection.cpp** (**main** target) 
CMakeLists.txt code
`set(CMAKE_PREFIX_PATH ../thirdparty/libtorch/)`
`find_package(Torch REQUIRED)`
`target_link_libraries(${PROJECT_NAME} PUBLIC v4l2lib processing ${TORCH_LIBRARIES})`

same as I did in  **PROCESSING**  lib target

And then I get an error
`terminate called after throwing an instance of 'std::bad_alloc'`
`  what():  std::bad_alloc`
`Aborted (core dumped)`

Code in detection.cpp is

```
int main(){
    V4L2DeviceParameters param("/dev/video0", 0, 416, 416, 30, IOTYPE_MMAP, 0);
    V4l2Capture* videoCapture = V4l2Capture::create(param);
    std::cout << "YES" << std::endl;
    //timeval timeout;
    //bool isReadable = (videoCapture->isReadable(&timeout) == 1);
    //char* buffer = new char[460800];
    //size_t nb = videoCapture->read(buffer,460800);
}
```

So without linking Torch it works well. Any idea why it is crashing?

**Comment by mpromonet** [comment]
Hi @moskalt 

Maybe the debugger will give you more information. As I told you I ran exactly your code and it works on Ubuntu20.04. A possibility is that you are mixing objects that used different build option that brings problems between STL objects linked in torch and in libv4l2cpp.

Best Regards,
Michel.
