### ISSUE TITLE
Unable to create new instance of V4l2Capture after destroying original one

### ISSUE THREAD

**Issue by amitv87** [mpromonet/libv4l2cpp#6]
Get these messages when I start /dev/video0 once, delete it and start again

```
Cannot set format for device:/dev/video0 Device or resource busy
Cannot init device:/dev/video0
```

**Comment by amitv87** [comment]
Update:
Ran this after deleting the capture instance while process was alive

```
fuser /dev/video0
```

and got output

```
/dev/video0:         20808m
```

which means device isn't released properly.

**Comment by mpromonet** [comment]
Hi amitv87,
If the file is still open, something closing the device is missing.
Did you openned using mmap or read interface ?
At a glance, it seems that V4L2MmapDevice::captureStop is no more called.
Regards,
Michel.

**Comment by amitv87** [comment]
I had used mmap and that indeed solved the bug, added captureStop call in V4L2MmapDevice destructor.
Thanks 👍

**Comment by mpromonet** [comment]
Hi,
Ok, I am moving captureStart and captureStop in the V4l2MmapDevice.
I will push this soon.
Thanks for the bug reporting.
Michel.
