### ISSUE TITLE
install: target '/usr/include/libv4l2cpp/' is not a directory: No such file or directory

### ISSUE THREAD

**Issue by devsheen** [mpromonet/libv4l2cpp#8]
On running sudo make install I get the following error:

pi@raspberrypi:~/libv4l2cpp $ sudo make install
install -D -m 0755 inc/*.h /usr/include/libv4l2cpp/
install: target '/usr/include/libv4l2cpp/' is not a directory: No such file or directory
Makefile:30: recipe for target 'install' failed
make: *** [install] Error 1

I fixed the error by first making the directory /usr/include/libv4l2cpp/

Adding "mkdir $(PREFIX)/include/libv4l2cpp/" to the makefile immediately before line 30 should fix the bug.

**Comment by mpromonet** [comment]
Hi Samuel,

Thanks for reporing this problem, you could submit a pull request to share your fix.

Best Regards,
Michel.

**Comment by mpromonet** [comment]
Fix by PR https://github.com/mpromonet/libv4l2cpp/pull/9
